CREATE USER postgres;
CREATE DATABASE coronattack;
GRANT ALL PRIVILEGES ON DATABASE coronattack TO postgres;
CREATE TABLE IF NOT EXISTS users
(
    id BIGSERIAL PRIMARY KEY NOT NULL, 
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL, 
    password VARCHAR(200) NOT NULL, 
    UNIQUE (email); 
);

