version: "3"


services:
  src:
    container_name: src
    build: ./src
    volumes:
      - ./src:/src
    ports:
      - 3000:3000
    working_dir: ./src
    stdin_open: true
    restart: always

  storage:
    container_name: storage
    build: ./src/storage
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coronattack
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:
