version: "3.4"

services:

  backend:
    image: backend
    build: ./backend/
    volumes:
      - ./backend:/backend
      - node_modules:/backend/node_modules
    environment:
      NODE_ENV: dev
    depends_on:
    - storage
    ports:
      - 3001:3001
      - 3002:3002

  frontend:
    image: frontend
    build: ./frontend/
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    
  storage:
    container_name: storage
    build: ./backend/storage
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coronattack
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:
  node_modules:
