version: "3"

services:

  storage:
    image: storage
    container_name: storage
    build: ./backend/storage
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: meta
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:
