version: "3.4"

services:
<<<<<<< HEAD
<<<<<<< HEAD

  backend:
    image: backend
    build:
      context: /backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - 3001:3002

  frontend:
    image: frontend
    build:
      context: /frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

=======
>>>>>>> 4089b818982fee084d12c86d8efbcd94cf6035a0
=======
>>>>>>> 4089b818982fee084d12c86d8efbcd94cf6035a0
  storage:
    container_name: storage
    build: ./backend/storage
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coronattack
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:



