version: "3"

services:
  react-app:
    container_name: react-app
    build:  ./
    volumes:
      - ./src:/src
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    working_dir: /src

  storage:
    container_name: storage
    build: ./src/storage
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coronattack
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:


